version: '3'

services:
  flask_app:
    container_name: flask_app
    build: .
    ports:
      - "5000:5000"
    env_file:
      - ./docker.env
    depends_on:
      - postgres
    restart: always
  postgres:
    container_name: flask_db
    image: postgres:12
    ports:
      - "5432:5432"
    env_file:
      - ./docker.env
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata: